# Generated by Django 5.1.3 on 2025-01-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_status_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='caminho_foto',
            field=models.ImageField(blank=True, upload_to='fotos'),
        ),
    ]
